### ISSUE TITLE
你好 我运行 python main.py时报错

### ISSUE THREAD

**Issue by Smmw** [alibaba/iOSSecAudit#3]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from smartconsole import *
  File "/Users/Yiming/GitHub/iOSSecAudit/smartconsole.py", line 6, in <module>
    from lib.taskutil import *
  File "/Users/Yiming/GitHub/iOSSecAudit/lib/taskutil.py", line 9, in <module>
    from device import *
  File "/Users/Yiming/GitHub/iOSSecAudit/lib/device.py", line 7, in <module>
    import numpy
ImportError: No module named numpy

**Comment by Smmw** [comment]
已经解决 我安装了 numpy  谢谢

**Comment by l3gi0nQQ** [comment]
@Smmw 
好的，最近github上的少，有问题可以在这里提，完了微博啥的提醒下我
